"""FRCNet public interfaces."""

from frcnet.data import (
    ALLOWED_COHORT_NAMES,
    BatchInput,
    ManifestBackedVisionDataset,
    SampleManifestRecord,
    build_plan_a_manifest,
    collate_manifest_samples,
    load_plan_a_source_datasets,
    read_manifest_jsonl,
    source_fingerprint_overlap,
    source_fingerprints,
    validate_manifest_records,
    validate_batch_input,
    write_manifest_jsonl,
)
from frcnet.evaluation import (
    MatchedManifestBinDiagnostic,
    MatchedBenchmarkSummary,
    MatchedManifestRecord,
    PropositionViewRecord,
    ReferenceScoreRecord,
    SampleAnalysisRecord,
    Top1PropositionRecord,
    build_frozen_matched_manifest,
    build_proposition_view_records,
    build_top1_proposition_records,
    read_reference_score_records,
    read_matched_manifest,
    read_proposition_view_records,
    read_sample_analysis_records,
    run_inference_export,
    state_content_entropy,
    state_entropy,
    state_weighted_content_entropy,
    summarize_matched_ambiguous_vs_ood,
    write_matched_benchmark_summary,
    write_matched_manifest,
    write_matched_manifest_bin_diagnostics,
    write_proposition_view_records,
    write_reference_score_records,
    write_sample_analysis_records,
    write_top1_proposition_records,
)
from frcnet.models import FRCNetModel, ModelOutput, SoftmaxReferenceModel, gradient_reverse
from frcnet.training import LossBreakdown, compute_total_loss, run_train_step
from frcnet.utils import (
    RuntimeSpec,
    completion_score,
    content_entropy,
    move_batch_to_device,
    resolve_runtime,
    resolution_weighted_content_entropy,
)

__all__ = [
    "__version__",
    "ALLOWED_COHORT_NAMES",
    "BatchInput",
    "FRCNetModel",
    "LossBreakdown",
    "ManifestBackedVisionDataset",
    "MatchedBenchmarkSummary",
    "MatchedManifestBinDiagnostic",
    "MatchedManifestRecord",
    "ModelOutput",
    "PropositionViewRecord",
    "ReferenceScoreRecord",
    "RuntimeSpec",
    "SampleAnalysisRecord",
    "SampleManifestRecord",
    "SoftmaxReferenceModel",
    "Top1PropositionRecord",
    "build_frozen_matched_manifest",
    "build_plan_a_manifest",
    "build_proposition_view_records",
    "build_top1_proposition_records",
    "collate_manifest_samples",
    "completion_score",
    "compute_total_loss",
    "content_entropy",
    "gradient_reverse",
    "load_plan_a_source_datasets",
    "move_batch_to_device",
    "read_manifest_jsonl",
    "source_fingerprint_overlap",
    "source_fingerprints",
    "read_matched_manifest",
    "read_proposition_view_records",
    "read_reference_score_records",
    "read_sample_analysis_records",
    "resolve_runtime",
    "resolution_weighted_content_entropy",
    "run_inference_export",
    "run_train_step",
    "state_content_entropy",
    "state_entropy",
    "state_weighted_content_entropy",
    "summarize_matched_ambiguous_vs_ood",
    "validate_batch_input",
    "validate_manifest_records",
    "write_manifest_jsonl",
    "write_matched_benchmark_summary",
    "write_matched_manifest",
    "write_matched_manifest_bin_diagnostics",
    "write_proposition_view_records",
    "write_reference_score_records",
    "write_sample_analysis_records",
    "write_top1_proposition_records",
]

__version__ = "0.6.0c0"
